# Generated by Django 6.0.3 on 2026-04-17 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantsInquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')], verbose_name='Phone Number')),
                ('interest', models.CharField(choices=[('Taining', 'Training'), ('Staffing', 'Staffing'), ('Consulting', 'Consulting')], max_length=20)),
                ('message', models.TextField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='partnersinquiries',
            old_name='details',
            new_name='description',
        ),
        migrations.AddField(
            model_name='partnersinquiries',
            name='job_location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnersinquiries',
            name='referral_source',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnersinquiries',
            name='skills_needed',
            field=models.CharField(choices=[('general', 'General Labor(No skills required)'), ('skilled', 'Skilled Labor(Experience required)')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
