# Generated by Django 6.0.3 on 2026-05-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_jobposting_alter_partnersinquiries_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantsinquiries',
            name='interest',
            field=models.CharField(choices=[('clerical', 'Clerical'), ('factory', 'Factory'), ('forklift_operator', 'Forklift Operator'), ('mover', 'Mover'), ('warehouse', 'Warehouse'), ('other', 'Other:')], max_length=20),
        ),
    ]
