# Generated by Django 6.0.3 on 2026-05-10 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_applicantsinquiries_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('TEMP', 'Temporary'), ('CONTRACT', 'Contract'), ('SEASONAL', 'Seasonal')], default='FT', max_length=20),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('drivers_license', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Do you have a valid Driver’s License?')),
                ('reliable_transportation', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Do you have reliable transportation?')),
                ('available_start_date', models.DateField(blank=True, null=True)),
                ('terms_and_conditions', models.BooleanField(default=False, verbose_name='I agree to the terms and conditions')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Reviewing'), ('INTERVIEW', 'Interview Scheduled'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main_app.jobposting')),
            ],
        ),
    ]
