# Generated by Django 6.0.3 on 2026-07-25 04:21

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantsinquiries',
            name='interest',
            field=models.CharField(choices=[('clerical', 'Clerical'), ('factory', 'Factory'), ('forklift_operator', 'Forklift Operator'), ('mover', 'Mover'), ('warehouse', 'Warehouse'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='partnersinquiries',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='partnersinquiries',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter a valid phone number (e.g. +15551234567).', max_length=128, region=None, unique=True),
        ),
    ]
