# Generated by Django 6.0.3 on 2026-07-25 19:31

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_applicantsinquiries_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersinquiries',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='partnersinquiries',
            name='skills_needed',
            field=models.CharField(choices=[('General', 'General Labor(No skills required)'), ('Skilled', 'Skilled Labor(Experience required)')], max_length=20),
        ),
    ]
