# Generated by Django 6.0.3 on 2026-07-25 20:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_partnersinquiries_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantsinquiries',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='applicantsinquiries',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
