# Generated by Django 6.0.3 on 2026-09-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_applicantsinquiries_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
