# Generated by Django 6.0.3 on 2026-09-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_jobposting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
