# Generated by Django 6.0.3 on 2026-09-13 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_jobposting_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms and Conditions', max_length=200)),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main_app.jobposting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='drivers_license',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Do you have a valid driver’s license?'),
        ),
    ]
